name: explore
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_animate: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  http: ^0.13.5
  intl: ^0.17.0
  provider: ^6.0.4
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/

  fonts:
    - family: Axiforma
      fonts:
        - asset: assets/fonts/Axiforma-Bold.otf
          weight: 700
        - asset: assets/fonts/Axiforma-Italic.otf
          style: italic
        - asset: assets/fonts/Axiforma-Medium.otf
          weight: 500
        - asset: assets/fonts/Axiforma-Regular.otf
          weight: 400
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
          weight: 400
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
